/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cubscout;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void rigerousTest() {
    assertTrue(true);
  }
}
